image: docker:24.0.3

pipelines:
  default:
    - step:
        services:
          - docker
        caches:
          - gradle
          - gradle-wrapper
          - docker
        script:
          - docker compose up -d
          - mkdir -p /usr/local/zulu \
            && wget https://cdn.azul.com/zulu/bin/zulu17.42.19-ca-jdk17.0.7-linux_musl_x64.tar.gz -O - \
            | tar -xz -f - -C /usr/local/zulu
          - JAVA_HOME=/usr/local/zulu/zulu17.42.19-ca-jdk17.0.7-linux_musl_x64 ./gradlew check

definitions:
  caches:
    gradle-wrapper: ~/.gradle/wrapper
