# With podman I've found that I have to recreate the machine with a mount to get compose to work
# podman machine stop
# podman machine rm
# podman machine init -v $(pwd)/docker-compose/pginit:/docker-entrypoint-initdb.d
# podman machine start
version: '3.5'

services:
  postgresql:
    image: postgres:15.3
    environment:
      POSTGRES_USER: 'word-games-dev'
      POSTGRES_PASSWORD: 'word-games-dev'
      POSTGRES_DB: 'word-games-dev'
    ports:
      - '127.0.0.1:25432:5432'
    networks:
      - word-games
    volumes:
      # one-time setup scripts
      - ./docker-compose/pginit/:/docker-entrypoint-initdb.d

networks:
  word-games:
    ipam:
      driver: default
      config:
        - subnet: 172.29.0.0/16
