version: '3.5'

services:
  postgresql:
    image: postgres:9.6
    environment:
      POSTGRES_USER: 'local-dev'
      POSTGRES_PASSWORD: 'local-dev'
      POSTGRES_DB: 'ktor-demo'
    ports:
      - '127.0.0.1:5432:5432'
